# default configuration

baseURL = "https://revsic.github.io"
languageCode = "ko-kr"
title = "revsic | ML Researcher"

theme = "liva-hugo"
summaryLength = "10"
paginate = 6
disqusShortname = ""

[outputs]
  home = ["HTML", "RSS", "JSON"]

[sitemap]
  changefreq = "daily"
  priority = 0.5
  filename = "sitemap.xml"

# plugins
[params.plugins]

  # CSS Plugins
  [[params.plugins.css]]
  URL = "plugins/bootstrap/bootstrap.min.css"
  [[params.plugins.css]]
  URL = "plugins/slick/slick.css"
  [[params.plugins.css]]
  URL = "plugins/themify-icons/themify-icons.css"
  [[params.plugins.css]]
  URL = "plugins/venobox/venobox.css"

  # JS Plugins
  [[params.plugins.js]]
  URL = "plugins/jQuery/jquery.min.js"
  [[params.plugins.js]]
  URL = "plugins/bootstrap/bootstrap.min.js"
  [[params.plugins.js]]
  URL = "plugins/slick/slick.min.js"
  [[params.plugins.js]]
  URL = "plugins/venobox/venobox.min.js"
  [[params.plugins.js]]
  URL = "plugins/search/fuse.min.js"
  [[params.plugins.js]]
  URL = "plugins/search/mark.js"
  [[params.plugins.js]]
  URL = "plugins/search/search.js"

  
# navigation
[menu]
  
  # main menu
  [[menu.main]]
  name = "About"
  URL = "about"
  weight = 1
  
  [[menu.main]]
  name = "Post"
  URL = "blog"
  weight = 2

  [[menu.main]]
  name = "CV"
  URL = "/pdf/cv.pdf"
  weight = 2

  # footer menu
  [[menu.footer]]
  name = "About"
  URL = "about"
  weight = 1
  
  [[menu.footer]]
  name = "Post"
  URL = "blog"
  weight = 2

  [[menu.footer]]
  name = "CV"
  URL = "/pdf/cv.pdf"
  weight = 2


# default parameters

[params]
home = "Home"

# Meta data
description = "revsic | ML Developer"
author = "YoungJoong Kim"

# Contact Information
email = "revsic99@gmail.com"
location = "Seoul, Korea"

# copyright
copyright = "| copyright &copy; 2020 [YoungJoong Kim](https://revsic.github.io) All Rights Reserved |"

  # Preloader
  [params.preloader]
  enable = true
  preloader = "" # use .png , .svg or .gif format

  # search
  [params.search]
  enable = true

# social site
# themify icon : https://themify.me/themify-icons

[[params.social]]
title = "github"
icon = "ti-github"
link = "https://github.com/revsic"

[[params.social]]
title = "linkedin"
icon = "ti-linkedin"
link = "https://www.linkedin.com/in/young-joong-kim-878630154/"
